### ISSUE TITLE
Failing test passes the CI

### ISSUE THREAD

**Issue by barmac** [camunda/zeebe-connection-test#13]
I am currently implementing a test with @camunda8/sdk. The test fails but the CI still reports a success: https://github.com/camunda/zeebe-connection-test/actions/runs/9174259442/job/25224729621
Perhaps it's due to `tee`.

**Comment by barmac** [comment]
I will fix this as suggested in https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command

**Comment by barmac** [comment]
Oh OK I just noticed that the tests rely on hard-coded value, so that's why it does not report failure of the third tool: https://github.com/camunda/zeebe-connection-test/blob/main/.github/workflows/CI.yml#L50

**Comment by nikku** [comment]
Did you understand how the tests previously worked? They checked if we received the respective amounts of `gateway` responses. If you add an additional test you'd need to bump the number to `3`.

However we fix it (https://github.com/camunda/zeebe-connection-test/commit/fec83d7c03472a46d2fd32930207ec536aa80ca1 or otherwise) I'd like to keep a working test, asserting that each of the tools report the expected gateway version (E2E test). We'd otherwise need to assume a failure is reported as a non-zero exit code (which I'm not sure about).
